#! /usr/bin/env python
import module_repertoire


# Autogenerated with DRAKON Editor 1.27

def dbg_prn(DEBUG, chaine):
    #item 39
    if DEBUG is True:
        #item 42
        print(chaine)
    else:
        pass


def main(liste_args):
    #item 203
    import module_parse
    parsed = module_parse.parse(liste_args)
    #item 192
    if parsed.first and parsed.top_level_dir:
        #item 200
        #print args.dir
        import module_racine
        tld = module_racine.Racine(parsed.top_level_dir)
        tld.pass1()
    else:
        pass
    #item 199
    """cas ou je veux afficher les tailles des repertoires"""
    #item 195
    if parsed.both and parsed.top_level_dir:
        #item 198
        #print args.dir
        import module_racine
        tld = module_racine.Racine(parsed.top_level_dir)
        tld.pass1()
        tld.pass2()
    else:
        pass

if __name__ == '__main__':
    import sys
    main(sys.argv[1:])
