# Autogenerated with DRAKON Editor 1.27

def parse(largs):
    #item 23
    import argparse
    Objet_parser = argparse.ArgumentParser()
    Objet_parser.add_argument(metavar="dir",help="name of the root directory", dest="top_level_dir")
    #item 24
    gmutex = Objet_parser.add_mutually_exclusive_group()
    gmutex.add_argument("-1", "--pass1", action="store_true", help="Run pass1, that computes .du in all subdirs", dest="first")
    gmutex.add_argument("-b","--both-passes", action="store_true", help="Run pass 1, that computes .du in all subdirs, and then pass 2 that is interactive", dest="both")
    gmutex.add_argument("-i","--interactive",action="store_true", help="Run pass 2 wich is interactive")
    #item 20
    Objet_parser.add_argument("-v","--verbose", help="turn on verbose output",  action="store_true", dest="verbose")
    #item 25
    return Objet_parser.parse_args(largs)


